apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohttp
  labels:
    app: gohttp
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gohttp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gohttp
    spec:
      containers:
        - image: scratch/gohttp:v1
          imagePullPolicy: Never
          name: gohttp
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: gohttp
  labels:
    app: gohttp
spec:
  type: NodePort
  selector:
    app: gohttp
  ports:
    - name: gohttp
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32767
